// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo2jRz_lCU4tBteOjoLhzi_qc88bL1sc4',
    appId: '1:662359775553:web:4eec319e3c84d1106369c0',
    messagingSenderId: '662359775553',
    projectId: 'flutterxfirebaseproj',
    authDomain: 'flutterxfirebaseproj.firebaseapp.com',
    storageBucket: 'flutterxfirebaseproj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa3ZDqzoa6Lr7ftBtuH81SG4WTseWrl18',
    appId: '1:662359775553:android:abf604099de6ca486369c0',
    messagingSenderId: '662359775553',
    projectId: 'flutterxfirebaseproj',
    storageBucket: 'flutterxfirebaseproj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYf4K60QkGc07P0hnegL4Oo6dkzg1UhYw',
    appId: '1:662359775553:ios:4899ff327fa8daab6369c0',
    messagingSenderId: '662359775553',
    projectId: 'flutterxfirebaseproj',
    storageBucket: 'flutterxfirebaseproj.appspot.com',
    iosBundleId: 'com.example.firebaseproject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYf4K60QkGc07P0hnegL4Oo6dkzg1UhYw',
    appId: '1:662359775553:ios:4899ff327fa8daab6369c0',
    messagingSenderId: '662359775553',
    projectId: 'flutterxfirebaseproj',
    storageBucket: 'flutterxfirebaseproj.appspot.com',
    iosBundleId: 'com.example.firebaseproject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo2jRz_lCU4tBteOjoLhzi_qc88bL1sc4',
    appId: '1:662359775553:web:1593c0a888f6b01b6369c0',
    messagingSenderId: '662359775553',
    projectId: 'flutterxfirebaseproj',
    authDomain: 'flutterxfirebaseproj.firebaseapp.com',
    storageBucket: 'flutterxfirebaseproj.appspot.com',
  );
}